import { article$$, content$$, contentBlock$$, contentFeatureItem$$, contentImage$$, contentParts$$, contentTestimonial$$, image$$, page$$, query$, testimonialAuthor$$ } from '../__generated/fetchers'

export const queryGetPage = query$.getPage(page$$
	.blocks(
		{},
		contentBlock$$
		.images(
			{},
			contentImage$$
			.image(
				{},
				image$$
				.articleFeaturedimage(
					{},
					article$$
					.content(
						{},
						content$$
						.parts(
							{},
							contentParts$$
						)
						.contentfeatureitemContent(
							{},
							contentFeatureItem$$
						)
						.contenttestimonialContent(
							{},
							contentTestimonial$$
							.author(
								{},
								testimonialAuthor$$
							)
						)
					)
				)
				.testimonialauthorImage(
					{},
					testimonialAuthor$$
					.testimonial(
						{},
						contentTestimonial$$
						.content(
							{},
							content$$
							.parts(
								{},
								contentParts$$
							)
							.articleContent(
								{},
								article$$
							)
							.contentfeatureitemContent(
								{},
								contentFeatureItem$$
							)
						)
					)
				)
			)
		)
		.content(
			{},
			content$$
			.parts(
				{},
				contentParts$$
			)
			.articleContent(
				{},
				article$$
				.featuredImage(
					{},
					image$$
					.contentimageImage(
						{},
						contentImage$$
					)
					.testimonialauthorImage(
						{},
						testimonialAuthor$$
						.testimonial(
							{},
							contentTestimonial$$
						)
					)
				)
			)
			.contentfeatureitemContent(
				{},
				contentFeatureItem$$
			)
			.contenttestimonialContent(
				{},
				contentTestimonial$$
				.author(
					{},
					testimonialAuthor$$
					.image(
						{},
						image$$
						.articleFeaturedimage(
							{},
							article$$
						)
						.contentimageImage(
							{},
							contentImage$$
						)
					)
				)
			)
		)
		.featureList(
			{},
			contentFeatureItem$$
			.content(
				{},
				content$$
				.parts(
					{},
					contentParts$$
				)
				.articleContent(
					{},
					article$$
					.featuredImage(
						{},
						image$$
						.contentimageImage(
							{},
							contentImage$$
						)
						.testimonialauthorImage(
							{},
							testimonialAuthor$$
							.testimonial(
								{},
								contentTestimonial$$
							)
						)
					)
				)
				.contenttestimonialContent(
					{},
					contentTestimonial$$
					.author(
						{},
						testimonialAuthor$$
						.image(
							{},
							image$$
							.articleFeaturedimage(
								{},
								article$$
							)
							.contentimageImage(
								{},
								contentImage$$
							)
						)
					)
				)
			)
		)
		.testimonials(
			{},
			contentTestimonial$$
			.content(
				{},
				content$$
				.parts(
					{},
					contentParts$$
				)
				.articleContent(
					{},
					article$$
					.featuredImage(
						{},
						image$$
						.contentimageImage(
							{},
							contentImage$$
						)
						.testimonialauthorImage(
							{},
							testimonialAuthor$$
						)
					)
				)
				.contentfeatureitemContent(
					{},
					contentFeatureItem$$
				)
			)
			.author(
				{},
				testimonialAuthor$$
				.image(
					{},
					image$$
					.articleFeaturedimage(
						{},
						article$$
						.content(
							{},
							content$$
							.parts(
								{},
								contentParts$$
							)
							.contentfeatureitemContent(
								{},
								contentFeatureItem$$
							)
						)
					)
					.contentimageImage(
						{},
						contentImage$$
					)
				)
			)
		)
	)
)